Purge data for auditor and dedupe tables
scoperetail-io/fusion-auditor pull request #14
Opened 2021-07-20 23:41 UTC by javierscope

2021-07-26 15:12 UTC, ravi-zadpide requested changes

2021-07-26 15:13 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/auditor/eraser/CommandImpl.java
> +  private static final String LOG_FILES = "auditor_log_file";
Done

2021-07-26 21:09 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/auditor/eraser/CommandImpl.java
> +  private String logsDirectory;
done

2021-08-05 16:29 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/auditor/config/SpringAuditorConfig.java
> +@ComponentScan(basePackages = {"com.scoperetail"})
Solved

2021-08-05 16:30 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/auditor/config/SpringAuditorConfig.java
> +@Import({FusionCoreConfig.class, ConfigProperties.class, SchedulerConfig.class})
Solved

2021-08-05 16:30 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/auditor/eraser/CommandImpl.java
> +  private String logsDirectory;
Solved

2021-08-05 16:30 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/auditor/eraser/CommandImpl.java
> +  private static final String LOG_FILES = "auditor_log_file";
Solved

2021-08-05 16:30 UTC, javierscope commented on src/main/resources/application-local.yml
> +logsDirectory: '/tmp/fusion/auditor/'
Solved

2021-08-05 16:30 UTC, javierscope commented on src/main/resources/application-walmart_prod.yml
> +logsDirectory: '/opt/fusion/target/fusion/auditor/'
Solved

2021-08-05 16:30 UTC, javierscope commented on src/main/resources/application-walmart_qa.yml
> +logsDirectory: '/opt/fusion/target/fusion/auditor/'
Solved

2021-08-05 16:32 UTC, merged